#/************************************************
#Author:		bigeast
#Time:		12/07/10 Tue 11:34:25 PM
#State:		correct
#Description:	Terminal Colors escape sequences
#************************************************/
#!/bin/bash
#Reset 
Color_Off='\e[0m'
echo    "-------------------------------------"
echo -e "Regular Colors\f\\\e\[0;30 ~ \\\e\[0;37"
echo    "-------------------------------------"
echo -e "\e[0;30m This is highlight text \e[0m"
echo -e "\e[0;31m This is highlight text \e[0m"
echo -e "\e[0;32m This is highlight text \e[0m"
echo -e "\e[0;33m This is highlight text \e[0m"
echo -e "\e[0;34m This is highlight text \e[0m"
echo -e "\e[0;35m This is highlight text \e[0m"
echo -e "\e[0;36m This is highlight text \e[0m"
echo -e "\e[0;37m This is highlight text \e[0m"
echo    "-------------------------------------"
echo -e "Bold\f\\\e[1;30 ~ \\\e[1;37"
echo    "-------------------------------------"
echo -e "\e[1;30m This is highlight text \e[0m"
echo -e "\e[1;31m This is highlight text \e[0m"
echo -e "\e[1;32m This is highlight text \e[0m"
echo -e "\e[1;33m This is highlight text \e[0m"
echo -e "\e[1;34m This is highlight text \e[0m"
echo -e "\e[1;35m This is highlight text \e[0m"
echo -e "\e[1;36m This is highlight text \e[0m"
echo -e "\e[1;37m This is highlight text \e[0m"
echo    "-------------------------------------"
echo -e "Underline\f\\\e[4;30 ~ \\\e[4;37"
echo -e "\e[4;30m This is highlight text \e[0m"
echo -e "\e[4;31m This is highlight text \e[0m"
echo -e "\e[4;32m This is highlight text \e[0m"
echo -e "\e[4;33m This is highlight text \e[0m"
echo -e "\e[4;34m This is highlight text \e[0m"
echo -e "\e[4;35m This is highlight text \e[0m"
echo -e "\e[4;36m This is highlight text \e[0m"
echo -e "\e[4;37m This is highlight text \e[0m"
  
echo    "-------------------------------------"
echo -e "Background\f\\\e[40 ~ \\\e[47"
echo    "-------------------------------------"
echo -e "\e[40m This is highlight text \e[0m"
echo -e "\e[41m This is highlight text \e[0m"
echo -e "\e[42m This is highlight text \e[0m"
echo -e "\e[43m This is highlight text \e[0m"
echo -e "\e[44m This is highlight text \e[0m"
echo -e "\e[45m This is highlight text \e[0m"
echo -e "\e[46m This is highlight text \e[0m"
echo -e "\e[47m This is highlight text \e[0m"
echo    "-------------------------------------"
echo -e "High Intensity\f\\\e[0;90 ~ \\\e[0;97"
echo    "-------------------------------------"
echo -e "\e[0;90m This is highlight text \e[0m"
echo -e "\e[0;91m This is highlight text \e[0m"
echo -e "\e[0;92m This is highlight text \e[0m"
echo -e "\e[0;93m This is highlight text \e[0m"
echo -e "\e[0;94m This is highlight text \e[0m"
echo -e "\e[0;95m This is highlight text \e[0m"
echo -e "\e[0;96m This is highlight text \e[0m"
echo -e "\e[0;97m This is highlight text \e[0m"
echo    "-------------------------------------"
echo -e "Bold High Intensity\f\\\e[1;90 ~ \\\e[1;97"
echo    "-------------------------------------"
echo -e "\e[1;90m This is highlight text \e[0m"
echo -e "\e[1;91m This is highlight text \e[0m"
echo -e "\e[1;92m This is highlight text \e[0m"
echo -e "\e[1;93m This is highlight text \e[0m"
echo -e "\e[1;94m This is highlight text \e[0m"
echo -e "\e[1;95m This is highlight text \e[0m"
echo -e "\e[1;96m This is highlight text \e[0m"
echo -e "\e[1;97m This is highlight text \e[0m"
