#!/bin/bash
USAGE="Usage: $0 [-e -f] str1 str2 str3 ... strN"
if [ "$#" == "0" ];then
echo "$USAGE"
exit 1
fi

if [ "$1" != "" ];then
	case $1 in
		-e)
		while [ "$2" ];do
		echo $2|tr 'a-zA-Z' 'n-za-mN-ZA-M'
		shift
		done
			;;
		-f)
		while [ "$2" ];do
		cat $2|tr 'a-zA-Z' 'n-za-mN-ZA-M'
		shift
		done
			;;
		*)  echo $USAGE
			exit 1
	esac
fi
