#!/usr/bin/bash

#	/etc/conf.d/network
################################
#	interface=wlan0
#	address=192.168.0.10
#	netmask=24
#	broadcast=192.168.0.255
#	gateway=192.168.0.1
################################
# FAST_5D9858 PIN:12510085
# /etc/wpa_suppilant/fast.conf
# $wpa_passphrase 'essid' 'passwd' > fast.conf
# CONF_FILE=/etc/wpa_supplicant/fast.conf

# Connect to open wireless network
if [ $1 == "-o" ]; then
	if [ -n $2 ]; then
		sudo iwconfig wlan0 essid $2
		sudo dhclient wlan0
		exit
	else
		echo -e "If you want to connect to an open wireless network...\n Usage:\fwlan -o [essid]"
	fi
	exit
fi

if [[ $1 == "restart" ]]; then
	echo "Set wlan0 $1 ..."
	sudo pkill dhclient
	sudo pkill wpa
	sudo ip link set wlan0 down
	sudo ip link set wlan0 up
	echo "...OK"
	exit
fi
if [[ $1 == "down" || $1 == "up" ]]; then
	echo "Set wlan0 $1 ..."
	sudo pkill dhclient
	sudo pkill wpa
	sudo ip link set wlan0 $1
	echo "...OK"
	exit
fi

CONF_FILE=/etc/wpa_supplicant/$1.conf
if [ ! -f $CONF_FILE ]; then
	if [ $# != 2 ]; then
		# TODO:howto show color in the terminal?
		#echo -e 'Both \e[1;93 essid \e[40 and \e[1;93 passwd \e[40 are needed.'
		echo 'Both essid and passwd are needed.'
		echo -e "Usage:\fwlan [essid] [passwd]"
		exit
	else
		sudo wpa_passphrase $1 $2 > $CONF_FILE
	fi
fi

if [ -f $CONF_FILE ]; then
	sudo wpa_supplicant -B -i wlan0 -D wext -c $CONF_FILE
	sudo dhclient wlan0
fi
